version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-streaming-node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: node index.js
    env_file:
      - .env
